# ==========================================
#         GeneralControls Configuration
# ==========================================

# Combat System Settings
combat:
  # Duration of combat tag in seconds
  duration: 15

  # Commands allowed during combat
  allowed-commands:
    - "/msg"
    - "/tell"
    - "/w"
    - "/whisper"
    - "/reply"
    - "/r"
    - "/help"
    - "/rules"
    - "/discord"
    - "/website"
    - "/vote"

  # Combat messages (use & for color codes)
  messages:
    start: "&c&l[COMBAT] &cYou are now in combat for %duration% seconds!"
    end: "&a&l[COMBAT] &aYou are no longer in combat!"
    death: "&a&l[COMBAT] &aCombat ended due to death."
    kill: "&a&l[COMBAT] &aCombat ended - opponent eliminated."
    elytra: "&c&l[COMBAT] &cYou cannot use elytra while in combat!"
    command: "&c&l[COMBAT] &cYou cannot use commands while in combat! &c(%seconds%s remaining)"

# Discord Integration Settings
discord:
  # Discord server invite link
  invite: "https://discord.gg/S83934SWaA"

  promotion:
    # Enable/disable automatic Discord promotion
    enabled: true

    # Interval between promotions in minutes
    interval-minutes: 15

    # Promotion messages (use & for color codes)
    messages:
      - "&d🎮 &eJoin our Discord community! &b%invite%"
      - "&6💬 &fChat with other players on Discord: &a%invite%"
      - "&9📢 &eGet server updates and announcements on Discord! &d%invite%"
      - "&a🌟 &fConnect with the community: &b%invite%"
      - "&c🔥 &eDiscord server for events, giveaways and more! &6%invite%"

# Spawn System Settings
spawn:
  messages:
    set: "&a&l[SPAWN] &aSpawn location set to %location%&a!"
    teleport: "&a&l[SPAWN] &aTeleported to spawn!"
    not-set: "&cSpawn location has not been set yet!"
    failed: "&c&l[SPAWN] &cFailed to teleport to spawn! Please contact an administrator."
    no-permission: "&c&l[SPAWN] &cYou must be an operator to use this command!"

# TNT Minecart Settings
tnt-minecart:
  # Block TNT minecart placement and dispensing
  blocked: true
  message: "&c&l[BLOCKED] &cTNT Minecarts are disabled on this server!"

# Recipe Settings
recipes:
  mace:
    # Disable mace crafting
    disabled: true
    message: "&c&l[CRAFTING] &cMace crafting has been disabled!"

# General Messages
messages:
  player-only: "&cThis command can only be used by players!"
  no-permission: "&cYou don't have permission to use this command!"

# ==========================================
#              Plugin Information
# ==========================================
# Plugin: GeneralControls
# Author: ___Pumpkinn
# Version: 1.0-SNAPSHOT
#
# Color Codes:
# &0 = Black        &8 = Dark Gray
# &1 = Dark Blue    &9 = Blue
# &2 = Dark Green   &a = Green
# &3 = Dark Aqua    &b = Aqua
# &4 = Dark Red     &c = Red
# &5 = Dark Purple  &d = Light Purple
# &6 = Gold         &e = Yellow
# &7 = Gray         &f = White
# &l = Bold         &m = Strikethrough
# &n = Underline    &o = Italic
# &r = Reset        &k = Magic
# ==========================================